#!/bin/bash


# Set decoration geometry
berryc border_width       1.5
berryc inner_border_width 0
berryc title_height       0
berryc top_gap    	  10
berryc edge_gap		  10 10 10 10

# Set decoration colors
berryc focus_color         7b99b7
berryc unfocus_color       7b99b7
berryc inner_focus_color   2b303c
berryc inner_unfocus_color 2b303c
berryc text_focus_color    FFFFFF
berryc text_unfocus_color  FEFEFE

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "false"
berryc set_font    "SF Pro Display Bold-9"

# Autostart App
nitrogen --restore
dunst &
compton &
sxhkd -c $HOME/.config/berry/berry.conf &
